services:
  jenkins:
    container_name: jenkins_docker_compose
    build: .
    ports:
      - "8099:8080"
    privileged: true
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - net_jenkins

volumes:
  jenkins_home:

networks:
  net_jenkins:
